dist: bionic

language: python

os: linux

python: 3.6

virtualenv:
    system_site_packages: true

addons:
    apt:
        packages:
            - python3-pkgconfig # setup/build
            - swig              # setup/build
            - libeigen3-dev     # setup/build/install
            - python3-igraph    # install
            - python3-numpy     # setup/build/install
            - pylint3           # test

before_install:
    - pip3 install --upgrade cpplint # test
    - cpplint --recursive graphkernels/cppkernels
    - pylint3 setup.py graphkernels

install:
    - python3 setup.py build_ext
    - python3 setup.py install
    - python3 setup.py sdist

script:
    - cd ./Tutorial
    - python3 demo_mutag.py
    # The following requires sklearn package
    #- python3 demo_grid_search.py
