dist: bionic

language: python

os: linux

python: 3.6

virtualenv:
    system_site_packages: true

addons:
    apt:
        packages:
            - python3-pkgconfig # setup/build
            - swig              # setup/build
            - libeigen3-dev     # setup/build/install
            - python3-igraph    # install
            - python3-numpy     # setup/build/install

before_install:
    - pip3 install --upgrade black
    - pip3 install --upgrade cpplint
    - pip3 install --upgrade check-manifest
    - pip3 install --upgrade pylint
    - pip3 install --upgrade pyroma
    - make check

install:
    - make install

script:
    - make installcheck
